### ISSUE TITLE
Deprecate and remove AUR packages

### ISSUE THREAD

**Issue by Doccrazy** [Doccrazy/stash-electron#11]
The Arch Linux AUR packages stash-electron and stash-electron-git have been marked for deletion due to violation of some arbitrary guidelines (PRQ#26118 and PRQ#26119). 

They always were a nightmare to maintain and I don't think anybody actually uses them. Arch users can simply download the AppImage packages which also support auto update.

- delete the packages in AUR
- remove the build steps from CI build
- add deprecation note and updated instructions to readme

**Comment by habizzle** [comment]
I used them ;-) but I will migrate to the AppImage package then! Thanks for you work!!! ;-)
