### ISSUE TITLE
Crash on startup on Ubuntu 22.04

### ISSUE THREAD

**Issue by Areiser** [Doccrazy/stash-electron#13]
Stash hard crashes on startup on ubuntu 22.04 with an Nvidia GPU.

`[72205:0518/100447.357444:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.`

You can workaround this issue by starting with the flag `--in-process-gpu`, so it might be related to electron (I found the workaround in https://github.com/atom/atom/issues/23608 )

**Comment by Areiser** [comment]
Can confirm that an electron update to 18.1.0 fixes the issue, but there are breaking changes so the app does not render correctly anymore.

**Comment by Doccrazy** [comment]
Thanks for the feedback!

Could you try the Electron 17 version that I am currently working on? It is available on the branch https://github.com/Doccrazy/stash-electron/tree/upgrade-to-electron-17 but not yet released.

Unfortunately, the upgrade to Electron 18 is currently blocked by the nodegit native dependency, as there is no prebuilt release available for the new version yet.

**Comment by Areiser** [comment]
Hi, thanks for the quick response, I didn't realize there was already a branch for an electron upgrade.

The electron 17 version also fixes the issue :+1:
